linear Algebra <br>
Universal Function <br>
stack <br>
in1d <br>

In [3]:
l=[1,2,3,4,5]
l[:2]

[1, 2]

In [2]:
import numpy as np

In [8]:
l=np.array([1,2,3,4,5,6])
print(l[:2])
l[:2]=5
print(l[:2])
l

[1 2]
[5 5]


array([5, 5, 3, 4, 5, 6])

In [19]:
l=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
l

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
l[:1,:1]

array([[1]])

In [4]:
a=np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [10]:
print(a[:2])
print(a[0:2])
print(a[-3:-1])


[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]
[[0 1 2 3]
 [4 5 6 7]]


In [11]:
a=np.arange(9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
a[:2,1:]

array([[1, 2],
       [4, 5]])

In [13]:
data=np.random.randn(7,4)
data

array([[-0.48007335,  0.0556838 ,  0.2832186 ,  0.70636767],
       [ 0.84671525, -0.31775681, -1.18987178,  0.73365267],
       [ 0.33928052,  0.23584105, -0.37185017,  0.01820987],
       [ 1.26263274, -0.84441157,  0.47991277,  0.37179532],
       [ 0.72593721,  0.28770648,  0.02964197,  1.05246136],
       [-0.6476993 ,  1.11336191,  1.45688087,  1.06617264],
       [-2.06840833, -0.93435489, -1.26831832, -0.66450835]])

In [14]:
names=np.array(['bob','joe','will','bob','will','joe','joe'])
names

array(['bob', 'joe', 'will', 'bob', 'will', 'joe', 'joe'], dtype='<U4')

In [26]:
~(names=='bob')

array([False,  True,  True, False,  True,  True,  True])

In [25]:
data[(names=='bob') | (names=='will')][:,[0,1]]

array([[-0.48007335,  0.0556838 ],
       [ 0.33928052,  0.23584105],
       [ 1.26263274, -0.84441157],
       [ 0.72593721,  0.28770648]])

In [34]:
data= np.arange(9).reshape(3,3)
data

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [35]:
data.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

In [43]:
a= np.arange(2*2*4).reshape(2,2,4)
a

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [44]:
a.transpose((1,0,2))

array([[[ 0,  1,  2,  3],
        [ 8,  9, 10, 11]],

       [[ 4,  5,  6,  7],
        [12, 13, 14, 15]]])

In [46]:
a.transpose??

# Universal Function: Fast Element-Wise Array Function

In [47]:
a=np.array([1,2,-3,4,-5,6,9])
print(np.abs(a))

[1 2 3 4 5 6 9]
