In [17]:
import numpy as np
a= np.arange(1,7)
b=a+5
print(a,b,sep='\n')

[1 2 3 4 5 6]
[ 6  7  8  9 10 11]


In [18]:
np.stack((a,b))

array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [19]:
np.stack((a,b),axis=1)

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10],
       [ 6, 11]])

In [20]:
np.column_stack((a,b))

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10],
       [ 6, 11]])

In [21]:
np.row_stack((a,b))

array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [22]:
np.hstack((a,b))

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [23]:
np.vstack((a,b))

array([[ 1,  2,  3,  4,  5,  6],
       [ 6,  7,  8,  9, 10, 11]])

In [24]:
np.block([a,b])

array([ 1,  2,  3,  4,  5,  6,  6,  7,  8,  9, 10, 11])

In [32]:
a= np.arange(1,2*2*2+1).reshape((2,2,2))
b=a+5
print(a,b,sep="\n->second\n")
np.dstack((a,b))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
->second
[[[ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]]]


array([[[ 1,  2,  6,  7],
        [ 3,  4,  8,  9]],

       [[ 5,  6, 10, 11],
        [ 7,  8, 12, 13]]])

In [40]:
a=np.arange(6*6).reshape(6,6)
print(a)

np.split(a,2,axis=1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]]


[array([[ 0,  1,  2],
        [ 6,  7,  8],
        [12, 13, 14],
        [18, 19, 20],
        [24, 25, 26],
        [30, 31, 32]]), array([[ 3,  4,  5],
        [ 9, 10, 11],
        [15, 16, 17],
        [21, 22, 23],
        [27, 28, 29],
        [33, 34, 35]])]

In [46]:
a=np.arange(2*2*2).reshape(2,2,2)
a
np.split(a,2)

[array([[[0, 1],
         [2, 3]]]), array([[[4, 5],
         [6, 7]]])]

# Broad Casting

In [15]:
a=np.random.randint(1,10,size=(3,5))
a

array([[1, 1, 1, 5, 8],
       [6, 5, 4, 5, 2],
       [3, 4, 9, 6, 4]])

# Array Set Operation

In [48]:
a=np.random.randint(1,10,size=20)
a

array([9, 3, 1, 4, 3, 3, 3, 1, 9, 6, 2, 8, 5, 1, 1, 3, 3, 5, 1, 7])

In [49]:
np.unique(a)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [53]:
a=np.random.randint(1,10,size=20)
b=np.random.randint(1,10,size=5)
print(a,b,sep="\n")

[True if x in a else False for x in b]

[4 9 2 5 3 9 7 3 8 9 8 3 4 8 9 2 2 4 5 3]
[2 4 3 6 2]


[True, True, True, False, True]

In [54]:
np.in1d(b,a)

array([ True,  True,  True, False,  True])

In [55]:
np.intersect1d(b,a)

array([2, 3, 4])

In [56]:
np.union1d(b,a)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.setxor1d(b,a)

array([5, 6, 7, 8, 9])

In [59]:
np.save("abc.npy",a)

In [60]:
b=np.load("abc.npy")

In [61]:
b

array([4, 9, 2, 5, 3, 9, 7, 3, 8, 9, 8, 3, 4, 8, 9, 2, 2, 4, 5, 3])