In [2]:
import numpy as np

In [3]:
%history

np.__version__
import numpy as np
%history


In [4]:
np.__version__

'1.16.5'

In [6]:
np.__version__

'1.16.5'

In [7]:
%time list(range(2000000))[:20]

Wall time: 107 ms


[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [9]:
%time np.arange(2000000)

Wall time: 22 ms


array([      0,       1,       2, ..., 1999997, 1999998, 1999999])

In [10]:
l=list(range(1,1000000))
l2=list(enumerate(l))

In [16]:
for i,v in l2:
    l[i]=l[i]+5
l[:20]

[16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35]

In [17]:
l= np.arange(1,1000000)
l=l+5
l

array([      6,       7,       8, ..., 1000002, 1000003, 1000004])

In [18]:
l.ndim

1

In [19]:
l.shape

(999999,)

# Dimensions

In [22]:
a=np.array([1,2,3,4])
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[1 2 3 4]
1
(4,)
int32


In [23]:
a=np.array([[1,2,3,4]
            ,[5,6,7,8]
            ,[9,10,11]])


[list([1, 2, 3, 4]) list([5, 6, 7, 8]) list([9, 10, 11])]
1
(3,)
object


In [29]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
print(a)
print(a.ndim)
print(a.shape)
print(a.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
int32


In [32]:
a=np.arange(1,10).reshape((3,3))
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
a=a+5

In [50]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [41]:
a=np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

### a[i,j,k]

In [46]:
#1st page
a[1]

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [47]:
a[1,0]

array([10, 11, 12])

In [49]:
a[1,0,2]

12

<img src="https://www.pythononformer.com/img/numpy/3d-array">

In [57]:
a=np.random.randn(2,3,3,4,5,5)
print(a.ndim)
print(a.shape)
a=a+a
a

6
(2, 3, 3, 4, 5, 5)


array([[[[[[-2.30201805e+00,  1.38457128e+00, -2.41970203e+00,
             5.85576601e-01, -8.37790413e-01],
           [ 4.15696850e+00, -1.90792904e+00, -2.08336337e+00,
             1.86516506e+00,  1.47348490e+00],
           [ 2.60906247e+00,  8.21935768e-01,  2.01389312e+00,
            -4.55419401e+00, -3.80093429e+00],
           [ 4.97431866e+00, -1.19742658e+00, -2.67743839e-01,
             1.52773133e-01,  4.39223868e-01],
           [ 1.64794476e+00, -1.82177341e+00, -9.89773910e-01,
             2.81868165e+00,  1.30168569e+00]],

          [[-3.90036505e+00,  1.14402519e+00,  1.98791778e+00,
             2.13891635e+00,  3.74046275e-02],
           [-3.17082146e+00, -3.56372279e+00,  1.29778508e+00,
             1.76635680e+00,  3.23833173e+00],
           [ 1.55274576e+00, -7.19589647e-01,  2.69063189e+00,
             3.45425124e-01, -4.54830070e-01],
           [ 8.74593742e-01,  2.37472402e+00,  8.82132425e-01,
            -1.83509987e+00, -1.00694628e+00],
        

In [66]:
b= np.random.randn(2,6)
print(b*b)

[[3.57657664e-01 7.97559309e-01 7.08911274e-01 5.41811156e+00
  5.79962387e-02 5.19257616e-01]
 [2.79600672e-01 1.83340317e+00 6.93959825e-01 1.58766863e-04
  5.62162399e-02 1.85127775e+00]]


In [67]:
b=np.arange(1,13).reshape((6,2))
b

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [68]:
b*b

array([[  1,   4],
       [  9,  16],
       [ 25,  36],
       [ 49,  64],
       [ 81, 100],
       [121, 144]])

# Creating ndarray

In [71]:
a=[1,2,3]
print(type(a))
a=np.array(a)
print(type(a))

<class 'list'>
<class 'numpy.ndarray'>


In [72]:
a=(1,2,3)
print(type(a))
a=np.array(a)
print(type(a))

<class 'tuple'>
<class 'numpy.ndarray'>


In [74]:
a={1,2,3}
print(type(a))
a=np.array(a)
print(type(a))

<class 'set'>
<class 'numpy.ndarray'>


In [75]:
a=[1,2,3]
print(type(a))
a=np.array(a)
print(type(a))

<class 'list'>
<class 'numpy.ndarray'>


# np.array

In [77]:
l=[1,2,3]
a=np.array(l)
b=np.array(a)
a is b

False

# np.asarray

In [78]:
l=[1,2,3]
a=np.asarray(l)
b=np.asarray(a)
a is b

True